### ISSUE TITLE
error on willie load

### ISSUE THREAD

**Issue by falmic** [chfoo/pleaseopme#1]
Error in pleaseopme setup procedure: super() takes at least 1 argument (0 given) (../../../../../../../.willie/modules/pleaseopme.py:155)

**Comment by chfoo** [comment]
I don't fully understand the situation. I need more info:
- How is Willie started?
- What version of Willie?
- What version of Python?
- What operating system?

**Comment by chfoo** [comment]
Closing due to staleness but please feel free to comment or open a new issue if needed.
