### ISSUE TITLE
Doesn't save and apply nicknames with ^ (caret symbol) correctly

### ISSUE THREAD

**Issue by UMLAUTaxl** [chfoo/pleaseopme#8]
I changed [irc/strings.py](https://github.com/jaraco/irc/blob/main/irc/strings.py) line 23 and 24 which will make it save the nicknames correctly but it won't apply them after rejoining the channel because it can't track them:
`DEBUG:__main__:Checking for auto priv in #testchannel234`
`DEBUG:__main__:Tracked ()`
`DEBUG:__main__:Tracked ()`

**Comment by UMLAUTaxl** [comment]
Sorry, some confusion.

**Comment by chfoo** [comment]
I changed it so that it won't modify `{}^` with a config option. Try restoring`irc/strings.py` to original, add `scandinavian=false` under `[irc]` in the ini file, and try with the updated code.

**Comment by UMLAUTaxl** [comment]
Thanks so much!
